"""Create Post table

Revision ID: 5897481c4faa
Revises: 
Create Date: 2024-07-27 03:51:07.399504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5897481c4faa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sentiment_pos', sa.Float(), nullable=False),
    sa.Column('sentiment_neg', sa.Float(), nullable=False),
    sa.Column('sentiment_neu', sa.Float(), nullable=False),
    sa.Column('sentiment_compound', sa.Float(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
